start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b
color a
color b