start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.batstart D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat
start D:\nb.bat